### ISSUE TITLE
DFT Bugs

### ISSUE THREAD

**Issue by MatheusNtg** [MatheusNtg/mgolgo#12]
The following cases are bugs:

### Case 1
When reading the file:
```
{ab}ab}
```
Current behaviour:
```
Classe: Comentário, Lexema: {ab}, Tipo: NULO
Classe: id, Lexema: ab, Tipo: NULO
Classe: , Lexema: }, Tipo: NULO
Classe: EOF, Lexema: , Tipo: NULO
```
Expected behaviour:
```
Classe: Comentário, Lexema: {ab}, Tipo: NULO
Erro na linha x coluna y, palavra ab} não existe na linguagem
Classe: ERRO, Lexema: , Tipo: NULO
Classe: EOF, Lexema: , Tipo: NULO
```
### Case 2

File:
```
{{abab}}
```
Current behaviour:
```
Classe: Comentário, Lexema: {{abab}, Tipo: NULO
Classe: , Lexema: }, Tipo: NULO
Classe: EOF, Lexema: , Tipo: NULO
```
Expected behaviour:
```
Classe: Comentário, Lexema: {{abab}, Tipo: NULO
Erro na linha x coluna y, palavra } não existe na linguagem
Classe: ERRO, Lexema: , Tipo: NULO
Classe: EOF, Lexema: , Tipo: NULO
````

### Case 3
File:
```
{{abab
```
Current behaviour:
```
Classe: , Lexema: {{abab, Tipo: NULO
Classe: EOF, Lexema: , Tipo: NULO
```
Expected behaviour:
```
Erro na linha x coluna y, palavra {{abab não existe na linguagem
Classe: ERRO, Lexema: , Tipo: NULO
Classe: EOF, Lexema: , Tipo: NULO
````

### Case 4
File:
```
abab}}
```
Current behaviour:
```
Classe: id, Lexema: abab, Tipo: NULO
Classe: , Lexema: }}, Tipo: NULO
Classe: EOF, Lexema: , Tipo: NULO
```
Expected behaviour:
```
Erro na linha x coluna y, palavra abab}} não existe na linguagem
Classe: ERRO, Lexema: , Tipo: NULO
Classe: EOF, Lexema: , Tipo: NULO
````

**Comment by alefiury** [comment]
In the following case:

> ### Case 4
> File:
> 
> ```
> abab}}
> ```
> 
> Current behaviour:
> 
> ```
> Classe: id, Lexema: abab, Tipo: NULO
> Classe: , Lexema: }}, Tipo: NULO
> Classe: EOF, Lexema: , Tipo: NULO
> ```
> 
> Expected behaviour:
> 
> ```
> Erro na linha x coluna y, palavra abab}} não existe na linguagem
> Classe: ERRO, Lexema: , Tipo: NULO
> Classe: EOF, Lexema: , Tipo: NULO
> ```

I think that the _Expected behaviour_ would be actually:

```
Erro na linha x coluna y, palavra abab} não existe na linguagem
Classe: ERRO, Lexema: , Tipo: NULO
Erro na linha x coluna y, palavra } não existe na linguagem
Classe: ERRO, Lexema: , Tipo: NULO
Classe: EOF, Lexema: , Tipo: NULO
```

Considering that the _Expected behaviour_ of Case 2 is:

> ```
> Classe: Comentário, Lexema: {{abab}, Tipo: NULO
> Erro na linha x coluna y, palavra } não existe na linguagem
> Classe: ERRO, Lexema: , Tipo: NULO
> Classe: EOF, Lexema: , Tipo: NULO
> ```

In which the word is broken down into two different parts: _**{{abab}**_ and _**}**_.

**Comment by MatheusNtg** [comment]
> {{abab}}

I agree on that

**Comment by MatheusNtg** [comment]
> In the following case:
> 
> > ### Case 4
> > File:
> > ```
> > abab}}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Current behaviour:
> > ```
> > Classe: id, Lexema: abab, Tipo: NULO
> > Classe: , Lexema: }}, Tipo: NULO
> > Classe: EOF, Lexema: , Tipo: NULO
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Expected behaviour:
> > ```
> > Erro na linha x coluna y, palavra abab}} não existe na linguagem
> > Classe: ERRO, Lexema: , Tipo: NULO
> > Classe: EOF, Lexema: , Tipo: NULO
> > ```
> 
> I think that the _Expected behaviour_ would be actually:
> 
> ```
> Erro na linha x coluna y, palavra abab} não existe na linguagem
> Classe: ERRO, Lexema: , Tipo: NULO
> Erro na linha x coluna y, palavra } não existe na linguagem
> Classe: ERRO, Lexema: , Tipo: NULO
> Classe: EOF, Lexema: , Tipo: NULO
> ```
> 
> Considering that the _Expected behaviour_ of Case 2 is:
> 
> > ```
> > Classe: Comentário, Lexema: {{abab}, Tipo: NULO
> > Erro na linha x coluna y, palavra } não existe na linguagem
> > Classe: ERRO, Lexema: , Tipo: NULO
> > Classe: EOF, Lexema: , Tipo: NULO
> > ```
> 
> In which the word is broken down into two different parts: _**{{abab}**_ and _**}**_.

I agree on that
